# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-25 00:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_auto_20171113_2238'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oneonone',
            name='contact',
        ),
        migrations.AddField(
            model_name='oneonone',
            name='contact',
            field=models.ManyToManyField(null=True, to='tracker.Contact'),
        ),
    ]
